'use client';

import { useEffect, useMemo, useState } from 'react';
import { Activity, BarChart3, Building2, CheckCircle2, Database, Filter, HardDrive, RefreshCw, Search, ShieldCheck, SlidersHorizontal, Users, XCircle } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { useEconexoData, type PlatformAuditRecord, type PlatformOrganization } from '@/lib/econexo-data';

const formatNumber = (value: number) => new Intl.NumberFormat('es-HN').format(value);
const formatBytes = (value: number) => value < 1024 * 1024 ? `${Math.max(0, Math.round(value / 1024))} KB` : `${(value / 1024 / 1024).toFixed(2)} MB`;
const percent = (value: number, limit: number) => limit > 0 ? Math.min(100, Math.round((value / limit) * 100)) : 0;
const dateLabel = (value?: string | null) => value ? new Intl.DateTimeFormat('es-HN', { dateStyle: 'medium', timeStyle: 'short' }).format(new Date(value)) : 'Sin actividad';
type Section = 'summary' | 'companies' | 'users' | 'audit' | 'limits';

function Metric({ icon: Icon, label, value, tone = '' }: { icon: typeof Users; label: string; value: string; tone?: string }) {
  return <div className={`platform-global-metric ${tone}`}><Icon /><span><small>{label}</small><strong>{value}</strong></span></div>;
}
function UsageBar({ value, limit, label }: { value: number; limit: number; label: string }) {
  const used = percent(value, limit);
  return <div className="platform-usage-row"><div><span>{label}</span><b>{formatNumber(value)} / {formatNumber(limit)}</b></div><div className="platform-usage-track"><i style={{ width: `${used}%` }} className={used >= 90 ? 'danger' : used >= 70 ? 'warning' : ''} /></div><small>{used}% utilizado</small></div>;
}

export function PlatformAdminPanel() {
  const { platformOrganizations, platformAudit, refreshPlatform, refreshPlatformAudit, setOrganizationStatus, setPlatformMember, loading } = useEconexoData();
  const [section, setSection] = useState<Section>('summary');
  const [query, setQuery] = useState('');
  const [statusFilter, setStatusFilter] = useState<'all' | PlatformOrganization['status']>('all');
  const [sort, setSort] = useState<'name' | 'created' | 'users' | 'records'>('name');
  const [auditAction, setAuditAction] = useState('');
  const [auditOrganization, setAuditOrganization] = useState('');
  const [auditFrom, setAuditFrom] = useState('');
  const [auditTo, setAuditTo] = useState('');
  const [message, setMessage] = useState('');
  const [busyId, setBusyId] = useState('');
  useEffect(() => { void refreshPlatformAudit(); }, [refreshPlatformAudit]);
  const filteredOrganizations = useMemo(() => platformOrganizations.filter(org => { const matchesQuery = !query.trim() || `${org.name} ${org.slug}`.toLowerCase().includes(query.trim().toLowerCase()); return matchesQuery && (statusFilter === 'all' || org.status === statusFilter); }).sort((a, b) => sort === 'name' ? a.name.localeCompare(b.name) : sort === 'created' ? b.created_at.localeCompare(a.created_at) : sort === 'users' ? b.user_count - a.user_count : b.record_count - a.record_count), [platformOrganizations, query, statusFilter, sort]);
  const allUsers = useMemo(() => platformOrganizations.flatMap(org => org.users.map(user => ({ ...user, organizationId: org.id, organizationName: org.name }))).filter(user => !query.trim() || `${user.full_name} ${user.username ?? ''} ${user.organizationName}`.toLowerCase().includes(query.trim().toLowerCase())), [platformOrganizations, query]);
  const totals = useMemo(() => platformOrganizations.reduce((acc, org) => ({ organizations: acc.organizations + 1, active: acc.active + (org.status === 'active' ? 1 : 0), users: acc.users + org.user_count, records: acc.records + org.record_count, storage: acc.storage + org.storage_bytes }), { organizations: 0, active: 0, users: 0, records: 0, storage: 0 }), [platformOrganizations]);
  const updateStatus = async (organization: PlatformOrganization, status: PlatformOrganization['status']) => { setBusyId(organization.id); setMessage(''); try { await setOrganizationStatus(organization.id, status); setMessage('Estado actualizado.'); } catch (error) { setMessage(error instanceof Error ? error.message : 'No se pudo actualizar el estado.'); } finally { setBusyId(''); } };
  const updateMember = async (organizationId: string, userId: string, input: { role?: 'admin' | 'employee'; active?: boolean }) => { setBusyId(`${organizationId}:${userId}`); setMessage(''); try { await setPlatformMember(organizationId, userId, input); setMessage('Usuario actualizado.'); } catch (error) { setMessage(error instanceof Error ? error.message : 'No se pudo actualizar el usuario.'); } finally { setBusyId(''); } };
  const loadAudit = () => void refreshPlatformAudit({ organizationId: auditOrganization || undefined, action: auditAction || undefined, from: auditFrom || undefined, to: auditTo || undefined });
  const sections: [Section, string, typeof BarChart3][] = [['summary', 'Resumen', BarChart3], ['companies', 'Empresas', Database], ['users', 'Usuarios', Users], ['audit', 'Bitácora global', Activity], ['limits', 'Uso y límites', SlidersHorizontal]];
  return <div className="platform-admin-panel">
    <div className="settings-head row"><div><h2>Panel administrativo SaaS</h2><p>Control global de las empresas que utilizan Gavrion EcoSystems.</p></div><Button variant="outline" onClick={() => { void refreshPlatform(); loadAudit(); }} disabled={loading}><RefreshCw />Actualizar</Button></div>
    <div className="platform-admin-tabs" role="tablist">{sections.map(([id, label, Icon]) => <button key={id} role="tab" aria-selected={section === id} className={section === id ? 'active' : ''} onClick={() => setSection(id)}><Icon />{label}</button>)}</div>
    {message && <p className="platform-admin-message" role="status">{message}</p>}
    {section === 'summary' && <><div className="platform-global-metrics"><Metric icon={Building2} label="Empresas registradas" value={formatNumber(totals.organizations)} /><Metric icon={CheckCircle2} label="Empresas activas" value={formatNumber(totals.active)} tone="success" /><Metric icon={Users} label="Usuarios activos" value={formatNumber(totals.users)} /><Metric icon={Database} label="Registros operativos" value={formatNumber(totals.records)} /><Metric icon={HardDrive} label="Almacenamiento usado" value={formatBytes(totals.storage)} /></div><div className="platform-summary-grid"><section className="platform-subpanel"><header><div><h3>Actividad reciente</h3><p>Últimas acciones registradas en todas las empresas.</p></div><Button variant="ghost" onClick={() => setSection('audit')}>Ver bitácora</Button></header>{platformAudit.slice(0, 6).map(audit => <AuditRow key={audit.id} audit={audit} />)}{!platformAudit.length && <div className="platform-empty"><Activity /><span>Aún no hay actividad registrada.</span></div>}</section><section className="platform-subpanel"><header><div><h3>Empresas con mayor uso</h3><p>Ordenadas por cantidad de registros.</p></div><Button variant="ghost" onClick={() => setSection('limits')}>Ver límites</Button></header>{platformOrganizations.slice().sort((a, b) => b.record_count - a.record_count).slice(0, 5).map(org => <div className="platform-ranking" key={org.id}><span>{org.name}<small>{formatNumber(org.user_count)} usuarios</small></span><b>{formatNumber(org.record_count)}</b></div>)}</section></div></>}
    {(section === 'companies' || section === 'users' || section === 'limits') && <div className="platform-toolbar"><div className="platform-search"><Search /><input value={query} onChange={e => setQuery(e.target.value)} placeholder={section === 'users' ? 'Buscar usuario o empresa…' : 'Buscar empresa…'} /></div>{section !== 'users' && <><label className="platform-filter"><Filter /><select value={statusFilter} onChange={e => setStatusFilter(e.target.value as typeof statusFilter)}><option value="all">Todos los estados</option><option value="active">Activas</option><option value="suspended">Suspendidas</option><option value="pending">Pendientes</option></select></label><label className="platform-filter"><SlidersHorizontal /><select value={sort} onChange={e => setSort(e.target.value as typeof sort)}><option value="name">Ordenar por nombre</option><option value="created">Más recientes</option><option value="users">Más usuarios</option><option value="records">Más registros</option></select></label></>}</div>}
    {section === 'companies' && <div className="platform-org-list">{filteredOrganizations.map(organization => <OrganizationCard key={organization.id} organization={organization} busyId={busyId} updateStatus={updateStatus} />)}{!filteredOrganizations.length && <div className="platform-empty"><Building2 /><span>No hay empresas que coincidan con el filtro.</span></div>}</div>}
    {section === 'users' && <div className="platform-user-table"><div className="platform-table-head"><span>Usuario</span><span>Empresa</span><span>Rol</span><span>Estado</span><span /></div>{allUsers.map(user => <div className="platform-table-row" key={`${user.organizationId}:${user.id}`}><span><strong>{user.full_name}</strong><small>@{user.username || 'sin usuario'}</small></span><span>{user.organizationName}</span><select value={user.role} disabled={busyId === `${user.organizationId}:${user.id}`} onChange={e => void updateMember(user.organizationId, user.id, { role: e.target.value as 'admin' | 'employee' })}><option value="admin">Administrador</option><option value="employee">Empleado</option></select><button className={`platform-user-status ${user.active ? 'active' : ''}`} disabled={busyId === `${user.organizationId}:${user.id}`} onClick={() => void updateMember(user.organizationId, user.id, { active: !user.active })}>{user.active ? 'Activo' : 'Inactivo'}</button><ShieldCheck /></div>)}{!allUsers.length && <div className="platform-empty"><Users /><span>No hay usuarios que coincidan con el filtro.</span></div>}</div>}
    {section === 'limits' && <div className="platform-limit-list">{filteredOrganizations.map(org => <article className="platform-limit-card" key={org.id}><header><div><h3>{org.name}</h3><small>{org.status === 'active' ? 'Activa' : org.status === 'suspended' ? 'Suspendida' : 'Pendiente'} · Última actividad: {dateLabel(org.last_activity_at)}</small></div><span className={`platform-status ${org.status}`}><i />{org.status === 'active' ? 'Activa' : org.status === 'suspended' ? 'Suspendida' : 'Pendiente'}</span></header><UsageBar label="Usuarios" value={org.user_count} limit={org.max_users ?? 25} /><UsageBar label="Registros" value={org.record_count} limit={org.max_records ?? 100000} /><UsageBar label="Almacenamiento (KB)" value={Math.round(org.storage_bytes / 1024)} limit={Math.round((org.storage_limit_bytes ?? 1073741824) / 1024)} /></article>)}</div>}
    {section === 'audit' && <><div className="platform-audit-filters"><label>Empresa<select value={auditOrganization} onChange={e => setAuditOrganization(e.target.value)}><option value="">Todas las empresas</option>{platformOrganizations.map(org => <option value={org.id} key={org.id}>{org.name}</option>)}</select></label><label>Acción<select value={auditAction} onChange={e => setAuditAction(e.target.value)}><option value="">Todas</option><option value="INSERT">Creación</option><option value="UPDATE">Edición</option><option value="DELETE">Eliminación</option></select></label><label>Desde<input type="date" value={auditFrom} onChange={e => setAuditFrom(e.target.value)} /></label><label>Hasta<input type="date" value={auditTo} onChange={e => setAuditTo(e.target.value)} /></label><Button onClick={loadAudit}><Filter />Aplicar filtros</Button></div><div className="platform-audit-list">{platformAudit.map(audit => <AuditRow key={audit.id} audit={audit} />)}{!platformAudit.length && <div className="platform-empty"><Activity /><span>No hay actividad con los filtros seleccionados.</span></div>}</div></>}
  </div>;
}

function AuditRow({ audit }: { audit: PlatformAuditRecord }) { return <div className="platform-audit-row"><span className={`platform-audit-action ${audit.action.toLowerCase()}`}>{audit.action === 'INSERT' ? '+' : audit.action === 'UPDATE' ? '↻' : '−'}</span><span><strong>{audit.organization_name || 'Sin empresa'}</strong><small>{audit.table_name} · {audit.actor_name || 'Sistema'}</small></span><span><b>{audit.action === 'INSERT' ? 'Creación' : audit.action === 'UPDATE' ? 'Edición' : 'Eliminación'}</b><small>{dateLabel(audit.created_at)}</small></span></div>; }
function OrganizationCard({ organization, busyId, updateStatus }: { organization: PlatformOrganization; busyId: string; updateStatus: (organization: PlatformOrganization, status: PlatformOrganization['status']) => Promise<void> }) { return <article className="platform-org-card"><div className="platform-org-header"><span className={`platform-status ${organization.status}`}><i />{organization.status === 'active' ? 'Activa' : organization.status === 'suspended' ? 'Suspendida' : 'Pendiente'}</span><strong>{organization.name}</strong><small>{organization.slug} · Alta {new Date(organization.created_at).toLocaleDateString('es-HN')}</small></div><div className="platform-metrics"><span><Users />{formatNumber(organization.user_count)}<small>usuarios</small></span><span><Database />{formatNumber(organization.record_count)}<small>registros</small></span><span><HardDrive />{formatBytes(organization.storage_bytes)}<small>almacenamiento</small></span></div><details className="platform-users"><summary>Ver usuarios ({organization.user_count})</summary>{organization.users.map(user => <div key={user.id}><span>{user.full_name}<small>@{user.username || 'sin usuario'}</small></span><b>{user.role === 'admin' ? 'Admin' : 'Empleado'}</b><i className={user.active ? 'active' : ''}>{user.active ? 'Activo' : 'Inactivo'}</i></div>)}</details><div className="platform-org-actions"><Button disabled={busyId === organization.id || organization.status === 'active'} onClick={() => void updateStatus(organization, 'active')}><CheckCircle2 />Activar</Button><Button variant="outline" disabled={busyId === organization.id || organization.status === 'suspended'} onClick={() => void updateStatus(organization, 'suspended')}><XCircle />Suspender</Button></div></article>; }
